### ISSUE TITLE
write episode information in the middle of write process, and read it at begin of read process.

### ISSUE THREAD

**Issue by sometao** [seekloud/ESSF#1]
When i record a game, information like player list maybe change.
But I need get the player list at the begin of read process.

So I need something like a map which i can update in write process, and I can get the map at very begin.

**Comment by hongBry** [comment]
@sometao hi,
#### I will work this.
#### I will add "MutableInfoMap" Box to record game mutable information，which can be updated in write process, and got at very begin.

#### new api in read process：
```
def getMutableInfo(key:String): Option[Array[Byte]]
def mutableInfoIterable: Iterable[(String,Array[Byte])]
```

#### new api in write process:
```
def getMutableInfo(key:String):Option[Array[Byte]]
def putMutableInfo(key:String,value:Array[Byte]):Option[Array[Byte]]
def mutableInfoIterable: Iterable[(String,Array[Byte])]
```

**Comment by sometao** [comment]
Class name and method name may be too long?
Could get some shorter name(s)?

**Comment by hongBry** [comment]
@sometao  ok.
i have renamed class name and method name.
